sudo: false

language: python

python: 2.7

install:
  - pip install -r requirements.txt
  - python setup.py build develop
  - pip install nose coveralls

script:
  - python -c 'import sys; print(sys.path)'
  - nosetests --with-coverage --cover-package=auto_argcomplete

after_success:
  - coveralls

notifications:
  email: false
